### PR TITLE
Issues #386, #393: Update DG on `Model` component

### LINKED ISSUE #386: Update DG - Implementation `Candidate` model
- [ ] Based on title
- [ ] [Model component](https://ay2122s2-cs2103-f11-2.github.io/tp/DeveloperGuide.html#model-component) section

### LINKED ISSUE #393: Update DG - Model Component
To update diagrams used [here](https://ay2122s2-cs2103-f11-2.github.io/tp/DeveloperGuide.html#model-component)

### PR DESCRIPTION
**Pull request by domlimm**
@lzan98 leon tagging you to review because you're more familiar with the `Interview` portion to verify the model. Thanks! ❤️ 

Closes #386.
Closes #393.

### CODE REVIEW

**Review by lzan98 — CHANGES_REQUESTED** [review]
Hey Dom! The diagram might require another `InterviewSchedule` class and `ReadOnlyInterviewSchedule` because `AddressBook` only stores the candidates!

**Comment by domlimm** [comment]
> Hey Dom! The diagram might require another `InterviewSchedule` class and `ReadOnlyInterviewSchedule` because `AddressBook` only stores the candidates!

Noted! Let me make the changes now and get your review again. Will notify you via tele!

**Comment by domlimm** [comment]
@lzan98 hello sir! changes are up as per our discussion. thanks!!! 😍

**Review by lzan98 — APPROVED** [review]
LGTM 👍

**Pull request merged**
