### PR TITLE
Issue #192: Refactor `candidate` model

### LINKED ISSUE #192: To refactor `studentId` in `Candidate` model
- [x] To look into refactoring `studentId` i.e. `EXXXXXXX` and current `studentId` to be `AXXXXXXXX`
- [x] Update email
- [x] Update `equals` method
- [x] Update UI
- [x] Update test cases
- [x] Update preloaded data
- [x] More coming...

### PR DESCRIPTION
**Pull request by domlimm**
This PR consists of the following changes:
- Update format of `studentId` from `EXXXXXXX` to `AXXXXXXXX`
- Update test cases on this change

Closes #192 and #196.

@charmainehly @LeeEnEn @lzan98 @tiewweijian hey guys, do take note.
After this PR and PR #209 that address Issue #207, we now have to take in `email` when adding Candidate. (You can just hover to see the overview of the tagged PR/Issue, thanks!)

### CODE REVIEW

**Review by tiewweijian — CHANGES_REQUESTED** [review]
Hey Dom ! Thanks for the great work ! I found some bugs in this PR and thought will be good to change before merging in. 

Screenshot 2022-03-29 at 5 18 23 PM

The feedback given back to the user shows `id` to be `id/E0123456`

And also another question: for email, typing `e0123456@u.nus.edu` will give me an error because the E is not capitalised. Is this the intended usage? 

EDIT: entering student ID is not case sensitive (which looks good to me), but the email field is case sensitive. Should we standardise it?

**Comment by domlimm** [comment]
@tiewweijian wj very good points! nice catch on the issues! will make the changes asap. thanks for reviewing! 💘

**Review by tiewweijian — APPROVED** [review]
LGTM ! Thanks Dom ! 
Was thinking if we really need to push the codecov % up, we can split the `FocusCard` methods into another class called `FocusCardUtil` (so that it becomes testable)

**Comment by domlimm** [comment]
@tiewweijian i realised the overall codecov dropped was due to me merging commits from `master`. this PR shouldnt have touched any non-logic/model related files.

**Review by charmainehly — APPROVED** [review]
LGTM! Thank you for making the big changes! 👍

**Pull request merged**
